# Development overrides - use with: docker compose -f compose.yaml -f compose.dev.yaml up
services:
  apiserver:
    image: psanders/mikro:latest
    build:
      context: .
      dockerfile: mods/apiserver/Dockerfile

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: mikro-sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - ./mods/apiserver/data:/data
    command: sqlite_web -H 0.0.0.0 /data/mikro.db
    depends_on:
      - apiserver
    networks:
      - mikro-network
