/**
 * Copyright (C) 2026 by Mikro SRL. MIT License.
 *
 * The defaulted (at-risk) loans report: a branded PDF (+ canonical JSON) for
 * DEFAULTED and late-ACTIVE loans.
 *
 * Input mirrors the pre-migration `DefaultedReportRow[]` + `totalPrincipal`
 * shape — the apiserver
 * already resolves the DB and the per-loan notes summary (an LLM call made
 * upstream) before calling this definition; `summary` here is taken as
 * pre-generated input text, never generated by this module.
 */
import { z } from "zod/v4";
import { defineReport, type Report } from "./report.js";
import {
  brandHeader,
  kpiGrid,
  dataTable,
  section,
  footerNote,
  page,
  type KpiCell,
  type TableRow
} from "./blocks.js";
import type { ReportDocument } from "./renderer.js";
import { formatDop, formatPct, formatDateEs } from "./format.js";

// ==================== Input schema (DB-free, mirrors DefaultedReportRow) ====================

export const defaultedReportRowInputSchema = z.object({
  name: z.string(),
  nickname: z.string().nullish(),
  phone: z.string(),
  loanId: z.number().int().positive(),
  paymentFrequency: z.string(),
  /** Sum of completed INSTALLMENT payments. */
  totalPaid: z.number().nonnegative(),
  /** Sum of completed LATE_FEE (mora) payments. */
  moraCollected: z.number().nonnegative(),
  /** Pre-generated (LLM, upstream) notes summary; "" / absent renders as "Sin notas". */
  summary: z.string().nullish(),
  /** true = DEFAULTED status, false = ACTIVE but overdue (late). */
  isDefaulted: z.boolean()
});

export type DefaultedReportRowInput = z.infer<typeof defaultedReportRowInputSchema>;

export const defaultedReportInputSchema = z.object({
  rows: z.array(defaultedReportRowInputSchema),
  totalPrincipalAtRiskDop: z.number().nonnegative(),
  generatedAt: z.coerce.date().optional()
});

export type DefaultedReportInput = z.infer<typeof defaultedReportInputSchema>;

// ==================== Canonical data model ====================

export interface DefaultedReportRowData {
  name: string;
  nickname: string | null;
  phone: string;
  loanId: number;
  paymentFrequency: string;
  totalPaid: number;
  moraCollected: number;
  notes: string;
  isDefaulted: boolean;
}

/** The full typed defaulted-report data model — canonical; the PDF adds no new data. */
export interface DefaultedReportData {
  generatedAt: string;
  totalAtRisk: number;
  totalPrincipalAtRiskDop: number;
  /**
   * Sum of `moraCollected` across at-risk rows. Note: the existing row shape
   * only carries mora already *collected*, not a distinct "still owed"
   * figure — this is the best-available proxy for the Pencil "Mora
   * acumulada" KPI; flag to the data owner if a true accrued-but-uncollected
   * figure should be piped in from `evaluateSnapshot` in a later phase.
   */
  moraCollectedTotalDop: number;
  /** % of at-risk rows that are DEFAULTED (vs. merely late/ACTIVE). */
  defaultRatePct: number;
  rows: DefaultedReportRowData[];
}

/** Build the canonical defaulted-report data model from validated input. */
export function buildDefaultedReportData(input: DefaultedReportInput): DefaultedReportData {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  const rows: DefaultedReportRowData[] = input.rows.map((r) => ({
    name: r.name,
    nickname: r.nickname ? r.nickname : null,
    phone: r.phone,
    loanId: r.loanId,
    paymentFrequency: r.paymentFrequency,
    totalPaid: r.totalPaid,
    moraCollected: r.moraCollected,
    notes: r.summary && r.summary.trim().length > 0 ? r.summary.trim() : "Sin notas",
    isDefaulted: r.isDefaulted
  }));

  const defaultedCount = rows.filter((r) => r.isDefaulted).length;
  const moraCollectedTotalDop = rows.reduce((sum, r) => sum + r.moraCollected, 0);
  const defaultRatePct = rows.length > 0 ? (defaultedCount / rows.length) * 100 : 0;

  return {
    generatedAt,
    totalAtRisk: rows.length,
    totalPrincipalAtRiskDop: input.totalPrincipalAtRiskDop,
    moraCollectedTotalDop,
    defaultRatePct,
    rows
  };
}

// ==================== Presentation (page composition) ====================

function buildKpiCells(data: DefaultedReportData): KpiCell[] {
  return [
    { label: "Préstamos en riesgo", value: `${data.totalAtRisk}` },
    {
      label: "Principal en riesgo",
      value: formatDop(data.totalPrincipalAtRiskDop),
      emphasize: true
    },
    { label: "Mora acumulada", value: formatDop(data.moraCollectedTotalDop), emphasize: true },
    { label: "Tasa de mora", value: formatPct(data.defaultRatePct), emphasize: true }
  ];
}

function buildRows(data: DefaultedReportData): TableRow[] {
  return data.rows.map((r) => ({
    cells: {
      nombre: r.nickname ?? r.name,
      telefono: r.phone,
      prestamo: `${r.loanId}`,
      estado: "",
      mora: formatDop(r.moraCollected),
      notas: r.notes
    },
    status: {
      column: "estado",
      value: r.isDefaulted ? "Default" : "Atrasado",
      tone: r.isDefaulted ? "overdue" : "partial"
    }
  }));
}

/** Compose the 1-page defaulted-report document from the canonical data model. */
export function buildDefaultedReportDocument(data: DefaultedReportData): ReportDocument {
  const meta = [
    `Generado ${formatDateEs(data.generatedAt)}`,
    `${data.totalAtRisk} préstamo${data.totalAtRisk !== 1 ? "s" : ""} en riesgo`
  ];

  const p1 = page([
    brandHeader({
      title: "Préstamos en Riesgo",
      subtitle: "Cartera en mora y atrasada",
      meta
    }),
    kpiGrid({ cells: buildKpiCells(data), columns: 4 }),
    section("Préstamos en riesgo", [
      dataTable({
        columns: [
          { key: "nombre", header: "Nombre", weight: 1.5 },
          { key: "telefono", header: "Teléfono", weight: 1 },
          { key: "prestamo", header: "Préstamo", weight: 0.7, align: "right" },
          { key: "estado", header: "Estado", weight: 0.9 },
          { key: "mora", header: "Mora", weight: 1, align: "right" },
          { key: "notas", header: "Notas", weight: 2.5 }
        ],
        rows: buildRows(data)
      })
    ]),
    footerNote([
      `Reporte de cartera en riesgo · Generado ${formatDateEs(data.generatedAt)} · Documento generado automáticamente por Mikro.`
    ])
  ]);

  return { pages: [{ layout: p1 }] };
}

/** The defaulted report: validated at-risk rows in, JSON/PDF out. */
export const defaultedReport: Report<DefaultedReportData> = defineReport({
  name: "defaulted",
  inputSchema: defaultedReportInputSchema,
  buildData: buildDefaultedReportData,
  toDocument: buildDefaultedReportDocument
});
