/**
 * Copyright (C) 2026 by Mikro SRL. MIT License.
 *
 * The defaulted (at-risk) loans report: a branded PDF (+ canonical JSON) for
 * DEFAULTED and late-ACTIVE loans.
 *
 * Input mirrors the pre-migration `DefaultedReportRow[]` + `totalPrincipal`
 * shape — the apiserver
 * already resolves the DB and the per-loan notes summary (an LLM call made
 * upstream) before calling this definition; `summary` here is taken as
 * pre-generated input text, never generated by this module.
 */
import { z } from "zod/v4";
import { defineReport, type Report } from "./report.js";
import { composeReportPages } from "./compose.js";
import {
  BRAND,
  brandHeader,
  kpiGrid,
  dataTable,
  section,
  paginateRows,
  PAGE_HEIGHT,
  PAGE_PADDING,
  PAGE_GAP,
  type KpiCell,
  type TableRow,
  type TableColumn,
  type ReportElement
} from "./blocks.js";
import {
  headerHeight,
  kpiGridHeight,
  tableRowBudget,
  SECTION_TITLE_HEIGHT,
  FOOTER_HEIGHT,
  estimateNoteEntryHeight,
  paginateByEstimatedHeight,
  NOTES_ENTRY_SEPARATOR_PX,
  SAFETY_FACTOR
} from "./layout.js";
import type { ReportDocument } from "./renderer.js";
import { formatDop, formatPct, formatDateEs } from "./format.js";

// ==================== Input schema (DB-free, mirrors DefaultedReportRow) ====================

export const defaultedReportRowInputSchema = z.object({
  name: z.string(),
  nickname: z.string().nullish(),
  phone: z.string(),
  loanId: z.number().int().positive(),
  paymentFrequency: z.string(),
  /** Sum of completed INSTALLMENT payments. */
  totalPaid: z.number().nonnegative(),
  /** Sum of completed LATE_FEE (mora) payments. */
  moraCollected: z.number().nonnegative(),
  /** Pre-generated (LLM, upstream) notes summary; "" / absent renders as "Sin notas". */
  summary: z.string().nullish(),
  /** true = DEFAULTED status, false = ACTIVE but overdue (late). */
  isDefaulted: z.boolean()
});

export type DefaultedReportRowInput = z.infer<typeof defaultedReportRowInputSchema>;

export const defaultedReportInputSchema = z.object({
  rows: z.array(defaultedReportRowInputSchema),
  totalPrincipalAtRiskDop: z.number().nonnegative(),
  generatedAt: z.coerce.date().optional()
});

export type DefaultedReportInput = z.infer<typeof defaultedReportInputSchema>;

// ==================== Canonical data model ====================

export interface DefaultedReportRowData {
  name: string;
  nickname: string | null;
  phone: string;
  loanId: number;
  paymentFrequency: string;
  totalPaid: number;
  moraCollected: number;
  notes: string;
  isDefaulted: boolean;
}

/** The full typed defaulted-report data model — canonical; the PDF adds no new data. */
export interface DefaultedReportData {
  generatedAt: string;
  totalAtRisk: number;
  totalPrincipalAtRiskDop: number;
  /**
   * Sum of `moraCollected` across at-risk rows. Note: the existing row shape
   * only carries mora already *collected*, not a distinct "still owed"
   * figure — this is the best-available proxy for the Pencil "Mora
   * acumulada" KPI; flag to the data owner if a true accrued-but-uncollected
   * figure should be piped in from `evaluateSnapshot` in a later phase.
   */
  moraCollectedTotalDop: number;
  /** % of at-risk rows that are DEFAULTED (vs. merely late/ACTIVE). */
  defaultRatePct: number;
  rows: DefaultedReportRowData[];
}

/** Build the canonical defaulted-report data model from validated input. */
export function buildDefaultedReportData(input: DefaultedReportInput): DefaultedReportData {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  const rows: DefaultedReportRowData[] = input.rows.map((r) => ({
    name: r.name,
    nickname: r.nickname ? r.nickname : null,
    phone: r.phone,
    loanId: r.loanId,
    paymentFrequency: r.paymentFrequency,
    totalPaid: r.totalPaid,
    moraCollected: r.moraCollected,
    notes: r.summary && r.summary.trim().length > 0 ? r.summary.trim() : "Sin notas",
    isDefaulted: r.isDefaulted
  }));

  const defaultedCount = rows.filter((r) => r.isDefaulted).length;
  const moraCollectedTotalDop = rows.reduce((sum, r) => sum + r.moraCollected, 0);
  const defaultRatePct = rows.length > 0 ? (defaultedCount / rows.length) * 100 : 0;

  return {
    generatedAt,
    totalAtRisk: rows.length,
    totalPrincipalAtRiskDop: input.totalPrincipalAtRiskDop,
    moraCollectedTotalDop,
    defaultRatePct,
    rows
  };
}

// ==================== Presentation (page composition) ====================

function buildKpiCells(data: DefaultedReportData): KpiCell[] {
  return [
    { label: "Préstamos en riesgo", value: `${data.totalAtRisk}` },
    {
      label: "Principal en riesgo",
      value: formatDop(data.totalPrincipalAtRiskDop),
      emphasize: true
    },
    { label: "Mora acumulada", value: formatDop(data.moraCollectedTotalDop), emphasize: true },
    // The Pencil design's "N de M préstamos" sub only makes sense with a
    // total-portfolio-loan-count datum this model doesn't carry (only
    // at-risk rows are in scope here) — omitted rather than inventing a new
    // input field (JSON model stays exactly as-is, see module doc).
    { label: "Tasa de mora", value: formatPct(data.defaultRatePct), emphasize: true }
  ];
}

function buildRows(data: DefaultedReportData): TableRow[] {
  return data.rows.map((r) => ({
    cells: {
      nombre: r.nickname ?? r.name,
      telefono: r.phone,
      prestamo: `#${r.loanId}`,
      estado: "",
      mora: formatDop(r.moraCollected)
    },
    status: {
      column: "estado",
      value: r.isDefaulted ? "Default" : "Atrasado",
      tone: r.isDefaulted ? "overdue" : "partial"
    }
  }));
}

const TABLE_COLUMNS: TableColumn[] = [
  { key: "nombre", header: "Nombre", weight: 1.6, variant: "primary" },
  { key: "telefono", header: "Teléfono", weight: 1.2, variant: "secondary" },
  { key: "prestamo", header: "Préstamo", weight: 0.9, align: "right", variant: "secondary" },
  { key: "estado", header: "Estado", weight: 1 },
  { key: "mora", header: "Mora", weight: 1, align: "right", variant: "moneyEmphasis" }
];

/** One "Notas de cobro" entry: "Nombre — #loanId" + the full, unclamped note text. */
function buildNoteEntry(row: DefaultedReportRowData, isLast: boolean): ReportElement {
  return {
    type: "div",
    props: {
      style: {
        display: "flex",
        flexDirection: "column",
        gap: "4px",
        width: "100%",
        paddingBottom: "14px",
        ...(isLast ? {} : { borderBottom: `1px solid ${BRAND.border}` })
      },
      children: [
        {
          type: "div",
          props: {
            style: {
              fontFamily: "Inter",
              display: "flex",
              fontSize: "12px",
              fontWeight: 600,
              color: BRAND.ink
            },
            children: `${row.nickname ?? row.name} — #${row.loanId}`
          }
        },
        {
          type: "div",
          props: {
            style: {
              fontFamily: "Inter",
              display: "flex",
              fontSize: "11px",
              fontWeight: 500,
              color: BRAND.muted,
              lineHeight: 1.4
            },
            children: row.notes
          }
        }
      ]
    }
  };
}

/**
 * Compose the defaulted-report document from the canonical data model.
 * Usually 1 page; the at-risk table paginates when it overflows a fixed page
 * (see `layout.ts`'s `tableRowBudget` — the fix for the resvg crash in issue
 * #202). The Notas column left the table entirely (per the Pencil redesign
 * — a 4-line-clamped table cell was the #202-follow-up mitigation, not the
 * target shape) for its own "Notas de cobro" section, which ALWAYS starts on
 * a fresh page (user-approved) and paginates its variable-length entries by
 * estimated height instead of a row count.
 */
export function buildDefaultedReportDocument(data: DefaultedReportData): ReportDocument {
  const meta = [
    { label: "Generado", value: formatDateEs(data.generatedAt) },
    // No distinct "as of" cutoff exists in this model separate from
    // `generatedAt` — the Pencil "Corte" row mirrors it rather than
    // inventing a second timestamp the JSON model doesn't have.
    { label: "Corte", value: formatDateEs(data.generatedAt) }
  ];

  const firstPageAbove = [headerHeight(meta.length), kpiGridHeight(1, false)];
  const rowPages = paginateRows(
    buildRows(data),
    tableRowBudget({ aboveHeights: firstPageAbove }),
    tableRowBudget({ includeSectionTitle: false })
  );

  const tablePages: ReportElement[][] = rowPages.map((rows, i) => {
    const body: ReportElement[] = [];
    if (i === 0) {
      body.push(
        brandHeader({
          eyebrow: "Reporte",
          title: "Préstamos en Riesgo",
          subtitle: "Cartera atrasada y en incumplimiento",
          meta
        }),
        kpiGrid({ cells: buildKpiCells(data), columns: 4 }),
        section("Préstamos atrasados", [dataTable({ columns: TABLE_COLUMNS, rows })])
      );
    } else {
      body.push(dataTable({ columns: TABLE_COLUMNS, rows }));
    }
    return body;
  });

  // "Notas de cobro" always starts on its own fresh page (user-approved), so
  // its first entry-page uses the section-title-inclusive budget and any
  // further continuation page reclaims that height like the table pages do.
  const notesRows = data.rows.filter((r) => r.notes !== "Sin notas");
  const notesPages: ReportElement[][] = [];
  if (notesRows.length > 0) {
    const firstBudget = Math.floor(
      (PAGE_HEIGHT - 2 * PAGE_PADDING - SECTION_TITLE_HEIGHT - FOOTER_HEIGHT - PAGE_GAP) *
        SAFETY_FACTOR
    );
    const continuationBudget = Math.floor(
      (PAGE_HEIGHT - 2 * PAGE_PADDING - FOOTER_HEIGHT - PAGE_GAP) * SAFETY_FACTOR
    );
    const entryPages = paginateByEstimatedHeight(
      notesRows,
      (r) => estimateNoteEntryHeight(r.notes),
      firstBudget,
      continuationBudget,
      NOTES_ENTRY_SEPARATOR_PX
    );
    entryPages.forEach((rows, i) => {
      // A single flex-column wrapper (no extra gap — each entry already
      // carries its own separator via paddingBottom+borderBottom) used both
      // bare (continuation pages) and inside `section()` (first page), so
      // entry-to-entry spacing is identical either way.
      const entriesColumn: ReportElement = {
        type: "div",
        props: {
          style: { display: "flex", flexDirection: "column", width: "100%" },
          children: rows.map((r, ri) => buildNoteEntry(r, ri === rows.length - 1))
        }
      };
      notesPages.push(i === 0 ? [section("Notas de cobro", [entriesColumn])] : [entriesColumn]);
    });
  }

  const allPageBodies = [...tablePages, ...notesPages];
  const footerContext = `Mikro SRL — Reporte de cartera en riesgo · Generado ${formatDateEs(data.generatedAt)}`;

  return composeReportPages(allPageBodies, () => [footerContext]);
}

/** The defaulted report: validated at-risk rows in, JSON/PDF out. */
export const defaultedReport: Report<DefaultedReportData> = defineReport({
  name: "defaulted",
  inputSchema: defaultedReportInputSchema,
  buildData: buildDefaultedReportData,
  toDocument: buildDefaultedReportDocument
});
