/**
 * Copyright (C) 2026 by Mikro SRL. MIT License.
 *
 * The renewal-candidates report: a branded PDF (+ canonical JSON) for loans
 * near completion or already completed.
 *
 * Input mirrors the pre-migration `RenewalReportRow[]` shape — the apiserver
 * already resolves the DB and the per-loan renewal note (an LLM call made upstream)
 * before calling this definition; `candidateNote` here is taken as
 * pre-generated input text, never generated by this module.
 *
 * `suggestedAmountDop` is a new *optional* per-row field: the pre-migration
 * row type had no suggested-renewal-amount data at all, but the Pencil
 * "Renovación" design calls for a "Monto sugerido" KPI. Until the apiserver
 * computes a real suggestion (Phase E), callers may omit it and the KPI
 * renders "—".
 */
import { z } from "zod/v4";
import { defineReport, type Report } from "./report.js";
import {
  brandHeader,
  kpiGrid,
  dataTable,
  section,
  footerNote,
  page,
  type KpiCell,
  type TableRow
} from "./blocks.js";
import type { ReportDocument } from "./renderer.js";
import { formatDop, formatDateEs } from "./format.js";

// ==================== Input schema (DB-free, mirrors RenewalReportRow) ====================

export const renewalReportRowInputSchema = z.object({
  name: z.string(),
  phone: z.string(),
  loanId: z.number().int().positive(),
  paymentFrequency: z.string(),
  paymentsMade: z.number().int().nonnegative(),
  termLength: z.number().int().positive(),
  paymentRating: z.number().int().min(1).max(5),
  /** Pre-generated (LLM, upstream) renewal note; "" / absent renders as "—". */
  candidateNote: z.string().nullish(),
  isCompleted: z.boolean(),
  /** New optional field — see module doc. Absent → "Monto sugerido" KPI shows "—". */
  suggestedAmountDop: z.number().nonnegative().nullish()
});

export type RenewalReportRowInput = z.infer<typeof renewalReportRowInputSchema>;

export const renewalReportInputSchema = z.object({
  rows: z.array(renewalReportRowInputSchema),
  generatedAt: z.coerce.date().optional()
});

export type RenewalReportInput = z.infer<typeof renewalReportInputSchema>;

// ==================== Canonical data model ====================

/**
 * Three-way status pill required by the Pencil design (Activo/Completado/Por
 * terminar). The pre-migration row only carried a 2-way `isCompleted`
 * boolean; "Por terminar" is derived here from the remaining-cuotas count
 * (<=1 remaining and not completed) — a small, purely-computed refinement,
 * not new input data.
 */
export type RenewalRowStatus = "activo" | "completado" | "porTerminar";

const NEAR_COMPLETION_REMAINING_CUOTAS = 1;

export interface RenewalReportRowData {
  name: string;
  phone: string;
  loanId: number;
  paymentFrequency: string;
  paymentsMade: number;
  termLength: number;
  paymentRating: number;
  candidateNote: string;
  suggestedAmountDop: number | null;
  status: RenewalRowStatus;
}

/** The full typed renewal-report data model — canonical; the PDF adds no new data. */
export interface RenewalReportData {
  generatedAt: string;
  candidateCount: number;
  /** Non-completed candidates (mirrors the pre-migration "por terminar" summary count). */
  pendingCount: number;
  averageRating: number | null;
  /** Average of the per-row `suggestedAmountDop` supplied; null when none were. */
  suggestedAmountDop: number | null;
  rows: RenewalReportRowData[];
}

function statusFor(row: RenewalReportRowInput): RenewalRowStatus {
  if (row.isCompleted) return "completado";
  const remaining = row.termLength - row.paymentsMade;
  return remaining <= NEAR_COMPLETION_REMAINING_CUOTAS ? "porTerminar" : "activo";
}

/** Build the canonical renewal-report data model from validated input. */
export function buildRenewalReportData(input: RenewalReportInput): RenewalReportData {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  const rows: RenewalReportRowData[] = input.rows.map((r) => ({
    name: r.name,
    phone: r.phone,
    loanId: r.loanId,
    paymentFrequency: r.paymentFrequency,
    paymentsMade: r.paymentsMade,
    termLength: r.termLength,
    paymentRating: r.paymentRating,
    candidateNote:
      r.candidateNote && r.candidateNote.trim().length > 0 ? r.candidateNote.trim() : "—",
    suggestedAmountDop: r.suggestedAmountDop ?? null,
    status: statusFor(r)
  }));

  const pendingCount = rows.filter((r) => r.status !== "completado").length;
  const averageRating =
    rows.length > 0 ? rows.reduce((sum, r) => sum + r.paymentRating, 0) / rows.length : null;
  const suggestions = rows.map((r) => r.suggestedAmountDop).filter((v): v is number => v !== null);
  const suggestedAmountDop =
    suggestions.length > 0 ? suggestions.reduce((sum, v) => sum + v, 0) / suggestions.length : null;

  return {
    generatedAt,
    candidateCount: rows.length,
    pendingCount,
    averageRating,
    suggestedAmountDop,
    rows
  };
}

// ==================== Presentation (page composition) ====================

const STATUS_LABELS: Record<RenewalRowStatus, string> = {
  activo: "Activo",
  completado: "Completado",
  porTerminar: "Por terminar"
};

const STATUS_TONES: Record<RenewalRowStatus, "info" | "paid" | "partial"> = {
  activo: "info",
  completado: "paid",
  porTerminar: "partial"
};

const STAR = "★";

function buildKpiCells(data: RenewalReportData): KpiCell[] {
  return [
    { label: "Candidatos", value: `${data.candidateCount}` },
    { label: "Por terminar", value: `${data.pendingCount}` },
    {
      label: "Calif. promedio",
      value: data.averageRating !== null ? data.averageRating.toFixed(1) : "—"
    },
    {
      label: "Monto sugerido",
      value: data.suggestedAmountDop !== null ? formatDop(data.suggestedAmountDop) : "—"
    }
  ];
}

function buildRows(data: RenewalReportData): TableRow[] {
  return data.rows.map((r) => ({
    cells: {
      nombre: r.name,
      prestamo: `${r.loanId}`,
      estado: "",
      cuotas: `${r.paymentsMade}/${r.termLength}`,
      calif: STAR.repeat(r.paymentRating),
      nota: r.candidateNote
    },
    status: { column: "estado", value: STATUS_LABELS[r.status], tone: STATUS_TONES[r.status] }
  }));
}

/** Compose the 1-page renewal-report document from the canonical data model. */
export function buildRenewalReportDocument(data: RenewalReportData): ReportDocument {
  const meta = [
    `Generado ${formatDateEs(data.generatedAt)}`,
    `${data.candidateCount} candidato${data.candidateCount !== 1 ? "s" : ""}`
  ];

  const p1 = page([
    brandHeader({
      title: "Reporte de Renovación",
      subtitle: "Préstamos cerca de terminar o completados",
      meta
    }),
    kpiGrid({ cells: buildKpiCells(data), columns: 4 }),
    section("Candidatos de renovación", [
      dataTable({
        columns: [
          { key: "nombre", header: "Nombre", weight: 1.4 },
          { key: "prestamo", header: "Préstamo", weight: 0.7, align: "right" },
          { key: "estado", header: "Estado", weight: 1 },
          { key: "cuotas", header: "Cuotas", weight: 0.7, align: "right" },
          { key: "calif", header: "Calif.", weight: 0.8 },
          { key: "nota", header: "Nota de renovación", weight: 2.4 }
        ],
        rows: buildRows(data)
      })
    ]),
    footerNote([
      `Reporte de renovación · Generado ${formatDateEs(data.generatedAt)} · Documento generado automáticamente por Mikro.`
    ])
  ]);

  return { pages: [{ layout: p1 }] };
}

/** The renewal report: validated candidate rows in, JSON/PDF out. */
export const renewalReport: Report<RenewalReportData> = defineReport({
  name: "renewal",
  inputSchema: renewalReportInputSchema,
  buildData: buildRenewalReportData,
  toDocument: buildRenewalReportDocument
});
