/**
 * Copyright (C) 2026 by Mikro SRL. MIT License.
 *
 * The renewal-candidates report: a branded PDF (+ canonical JSON) for loans
 * near completion or already completed.
 *
 * Input mirrors the pre-migration `RenewalReportRow[]` shape — the apiserver
 * already resolves the DB and the per-loan renewal note (an LLM call made upstream)
 * before calling this definition; `candidateNote` here is taken as
 * pre-generated input text, never generated by this module.
 *
 * `suggestedAmountDop` is a new *optional* per-row field: the pre-migration
 * row type had no suggested-renewal-amount data at all, but the Pencil
 * "Renovación" design calls for a "Monto sugerido" KPI. Until the apiserver
 * computes a real suggestion (Phase E), callers may omit it and the KPI
 * renders "—".
 */
import { z } from "zod/v4";
import { defineReport, type Report } from "./report.js";
import { composeReportPages } from "./compose.js";
import {
  brandHeader,
  kpiGrid,
  dataTable,
  section,
  paginateRows,
  type KpiCell,
  type TableRow,
  type TableColumn,
  type ReportElement
} from "./blocks.js";
import { headerHeight, kpiGridHeight, tableRowBudget } from "./layout.js";
import type { ReportDocument } from "./renderer.js";
import { formatDop, formatDateEs } from "./format.js";

// ==================== Input schema (DB-free, mirrors RenewalReportRow) ====================

export const renewalReportRowInputSchema = z.object({
  name: z.string(),
  phone: z.string(),
  loanId: z.number().int().positive(),
  paymentFrequency: z.string(),
  paymentsMade: z.number().int().nonnegative(),
  termLength: z.number().int().positive(),
  paymentRating: z.number().int().min(1).max(5),
  /** Pre-generated (LLM, upstream) renewal note; "" / absent renders as "—". */
  candidateNote: z.string().nullish(),
  isCompleted: z.boolean(),
  /** New optional field — see module doc. Absent → "Monto sugerido" KPI shows "—". */
  suggestedAmountDop: z.number().nonnegative().nullish()
});

export type RenewalReportRowInput = z.infer<typeof renewalReportRowInputSchema>;

export const renewalReportInputSchema = z.object({
  rows: z.array(renewalReportRowInputSchema),
  generatedAt: z.coerce.date().optional()
});

export type RenewalReportInput = z.infer<typeof renewalReportInputSchema>;

// ==================== Canonical data model ====================

/**
 * Three-way status pill required by the Pencil design (Activo/Completado/Por
 * terminar). The pre-migration row only carried a 2-way `isCompleted`
 * boolean; "Por terminar" is derived here from the remaining-cuotas count
 * (<=1 remaining and not completed) — a small, purely-computed refinement,
 * not new input data.
 */
export type RenewalRowStatus = "activo" | "completado" | "porTerminar";

const NEAR_COMPLETION_REMAINING_CUOTAS = 1;

export interface RenewalReportRowData {
  name: string;
  phone: string;
  loanId: number;
  paymentFrequency: string;
  paymentsMade: number;
  termLength: number;
  paymentRating: number;
  candidateNote: string;
  suggestedAmountDop: number | null;
  status: RenewalRowStatus;
}

/** The full typed renewal-report data model — canonical; the PDF adds no new data. */
export interface RenewalReportData {
  generatedAt: string;
  candidateCount: number;
  /** Non-completed candidates (mirrors the pre-migration "por terminar" summary count). */
  pendingCount: number;
  averageRating: number | null;
  /** Average of the per-row `suggestedAmountDop` supplied; null when none were. */
  suggestedAmountDop: number | null;
  rows: RenewalReportRowData[];
}

function statusFor(row: RenewalReportRowInput): RenewalRowStatus {
  if (row.isCompleted) return "completado";
  const remaining = row.termLength - row.paymentsMade;
  return remaining <= NEAR_COMPLETION_REMAINING_CUOTAS ? "porTerminar" : "activo";
}

/** Build the canonical renewal-report data model from validated input. */
export function buildRenewalReportData(input: RenewalReportInput): RenewalReportData {
  const generatedAt = (input.generatedAt ?? new Date()).toISOString();

  const rows: RenewalReportRowData[] = input.rows.map((r) => ({
    name: r.name,
    phone: r.phone,
    loanId: r.loanId,
    paymentFrequency: r.paymentFrequency,
    paymentsMade: r.paymentsMade,
    termLength: r.termLength,
    paymentRating: r.paymentRating,
    candidateNote:
      r.candidateNote && r.candidateNote.trim().length > 0 ? r.candidateNote.trim() : "—",
    suggestedAmountDop: r.suggestedAmountDop ?? null,
    status: statusFor(r)
  }));

  const pendingCount = rows.filter((r) => r.status !== "completado").length;
  const averageRating =
    rows.length > 0 ? rows.reduce((sum, r) => sum + r.paymentRating, 0) / rows.length : null;
  const suggestions = rows.map((r) => r.suggestedAmountDop).filter((v): v is number => v !== null);
  const suggestedAmountDop =
    suggestions.length > 0 ? suggestions.reduce((sum, v) => sum + v, 0) / suggestions.length : null;

  return {
    generatedAt,
    candidateCount: rows.length,
    pendingCount,
    averageRating,
    suggestedAmountDop,
    rows
  };
}

// ==================== Presentation (page composition) ====================

const STATUS_LABELS: Record<RenewalRowStatus, string> = {
  activo: "Activo",
  completado: "Completado",
  porTerminar: "Por terminar"
};

const STATUS_TONES: Record<RenewalRowStatus, "info" | "paid" | "partial"> = {
  activo: "info",
  completado: "paid",
  porTerminar: "partial"
};

/** Month + year, e.g. "Julio 2026" — the Pencil header's "Período" meta value. Purely a display of `generatedAt`; no new data. */
function formatMonthYearEs(d: string | Date): string {
  const label = new Date(d).toLocaleDateString("es-DO", {
    month: "long",
    year: "numeric",
    timeZone: "UTC"
  });
  return label.charAt(0).toUpperCase() + label.slice(1);
}

function buildKpiCells(data: RenewalReportData): KpiCell[] {
  return [
    { label: "Candidatos", value: `${data.candidateCount}` },
    {
      label: "Por terminar",
      value: `${data.pendingCount}`,
      // "Máx." rather than "≤" — Inter has no glyph for U+2264 (confirmed
      // via opentype.js, same check as the star-rating fix above).
      subtext: `Máx. ${NEAR_COMPLETION_REMAINING_CUOTAS} cuota${NEAR_COMPLETION_REMAINING_CUOTAS === 1 ? "" : "s"} restante${NEAR_COMPLETION_REMAINING_CUOTAS === 1 ? "" : "s"}`
    },
    {
      label: "Calif. promedio",
      value: data.averageRating !== null ? data.averageRating.toFixed(1) : "—"
    },
    {
      label: "Monto sugerido",
      value: data.suggestedAmountDop !== null ? formatDop(data.suggestedAmountDop) : "—"
    }
  ];
}

function buildRows(data: RenewalReportData): TableRow[] {
  return data.rows.map((r) => ({
    cells: {
      nombre: r.name,
      prestamo: `#${r.loanId}`,
      estado: "",
      cuotas: `${r.paymentsMade} / ${r.termLength}`,
      // Plain "N/5" rather than a repeated star glyph (e.g. "★") — Inter has
      // no glyph for U+2605 (confirmed via opentype.js: charToGlyph returns
      // the .notdef/index-0 glyph), so a star rating rendered as tofu boxes
      // in every environment, not just the offline test font.
      calif: `${r.paymentRating}/5`,
      nota: r.candidateNote
    },
    status: { column: "estado", value: STATUS_LABELS[r.status], tone: STATUS_TONES[r.status] }
  }));
}

const TABLE_COLUMNS: TableColumn[] = [
  { key: "nombre", header: "Nombre", weight: 1.5, variant: "primary" },
  { key: "prestamo", header: "Préstamo", weight: 0.8, align: "right", variant: "secondary" },
  { key: "estado", header: "Estado", weight: 1.1 },
  { key: "cuotas", header: "Cuotas", weight: 0.8, align: "right", variant: "secondary" },
  { key: "calif", header: "Calif.", weight: 0.9, variant: "secondary" },
  { key: "nota", header: "Nota de renovación", weight: 2.6, variant: "secondary" }
];

/**
 * Compose the renewal-report document from the canonical data model. Usually
 * 1 page; the candidates table paginates when it overflows a fixed page (see
 * `layout.ts`'s `tableRowBudget`).
 */
export function buildRenewalReportDocument(data: RenewalReportData): ReportDocument {
  const meta = [
    { label: "Generado", value: formatDateEs(data.generatedAt) },
    { label: "Período", value: formatMonthYearEs(data.generatedAt) }
  ];

  const firstPageAbove = [headerHeight(meta.length), kpiGridHeight(1, true)];
  const rowPages = paginateRows(
    buildRows(data),
    tableRowBudget({ aboveHeights: firstPageAbove }),
    tableRowBudget({ includeSectionTitle: false })
  );

  const pageBodies: ReportElement[][] = rowPages.map((rows, i) => {
    const body: ReportElement[] = [];
    if (i === 0) {
      body.push(
        brandHeader({
          eyebrow: "Reporte",
          title: "Reporte de Renovación",
          subtitle: "Clientes elegibles para un nuevo ciclo",
          meta
        }),
        kpiGrid({ cells: buildKpiCells(data), columns: 4 }),
        section("Candidatos a renovación", [dataTable({ columns: TABLE_COLUMNS, rows })])
      );
    } else {
      body.push(dataTable({ columns: TABLE_COLUMNS, rows }));
    }
    return body;
  });

  const footerContext = `Mikro SRL — Reporte de renovación · Generado ${formatDateEs(data.generatedAt)}`;
  return composeReportPages(pageBodies, () => [footerContext]);
}

/** The renewal report: validated candidate rows in, JSON/PDF out. */
export const renewalReport: Report<RenewalReportData> = defineReport({
  name: "renewal",
  inputSchema: renewalReportInputSchema,
  buildData: buildRenewalReportData,
  toDocument: buildRenewalReportDocument
});
